version: '3.6'

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: pokemon-admin
      POSTGRES_PASSWORD: pokemon-password
      POSTGRES_DB: pokemon
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
      - '25:25'

  redoc:
    image: redocly/redoc
    ports:
      - 8081:80
    environment:
      SPEC_URL: http://localhost:3001/api/docs-json

volumes:
  postgresql:
  postgresql_data:
