export default {
    type: 'fire',
    stage: 'basic',
    name: '',
    nameEvolution: '',
    mainPicture: null,
    mainPictureX: -2,
    mainPictureY: 0,
    evolvePicture: null,
    evolvePictureX: 0,
    evolvePictureY: 0,
    hp: '30',
    weaknessType: '',
    weaknessAmount: '',
    resistanceType: '',
    resistanceAmount: '',
    retreat: '',
    retreatVisible: true,
    description: '',
    illustrator: 'Illus. ',
    cardNumber: '',
    totalCollection: '',
    rarity: '',
    species: '',
    length: '',
    weight: '',
    attack1: {
        attack1Name: '',
        attack1Dammage: '',
        attack1Info: '',
        attack1Type: '',
        attack1Amount: '1',
    },
    attack2: {
        attack2Name: '',
        attack2Dammage: '',
        attack2Info: '',
        attack2Type: '',
        attack2Amount: '1',
    },

    openedGroup: '',
}
